version: "3.5"

services:
    cloud_api:
        container_name: cloud_api
        build:
            context: .
        ports:
            - "5000:5000"
        environment:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
        volumes:
            - /app/data
        depends_on:
            - cloud_db

    cloud_db:
        container_name: cloud_db
        image: mongo
        environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        ports:
        - "27017:27017"
